# ClusterRoleBinding binds Clusterrole with Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2esa-cluster-role-name
rules:          # Authorization rules
  - apiGroups:  # 1st API group
      - ''      # An empty string designates the core API group.
      - extensions
    resources:
      - persistentvolumes
      - nodes
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - path
