apiVersion: apps/v1
kind: Deployment
metadata:
 name: e2esa-webapp01-deployment
 namespace: dev-webapp01
 labels:
  app: e2esa-webapp01
  tire: front-end
spec:
 replicas: 4
 template:
  metadata:
   name: e2esa-webapp01-pod
   labels:
    tire: front-end
    env: dev
    app: e2esa-webapp01
  spec:
   containers:
    - name: nginx
      image: nginx
 selector:
   matchLabels:
   tire: front-end
   env: dev
   app: e2esa-webapp01
