# refer: https://jfrog.com/blog/pulling-all-your-kubernetes-cluster-images-from-a-private-artifactory-registry/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2esa-webapp01-deployment
  namespace: dev-webapp01
  labels:
    app: e2esa-webapp01
spec:
  replicas: 4
  selector:
    matchLabels:
      app: e2esa-webapp01
  template:
    metadata:
      labels:
        app: e2esa-webapp01
    spec:
      containers:
      - name: my-app
        image: my-artifactory.jfrog.io/default-docker-virtual/my-app:1.0.1
        imagePullPolicy: Always
        imagePullSecrets:
        - name: regcred
        ports:
        - containerPort: 80
